// AUTO-GENERATED by scripts/gen_web_tokens.py — do not edit by hand.
// Source of truth: Assets/Themes/*.json (shared with PySide core/themes.py).
// WebUI consumes this to map /api/info theme_name to the data-am-theme
// slug emitted in themes.generated.css; keep both artifacts in sync by
// regenerating, never by hand-editing.

export const THEMES: { name: string; slug: string; dark: boolean }[] = [
  { name: 'Amber', slug: 'amber', dark: true },
  { name: 'Charcoal', slug: 'charcoal', dark: true },
  { name: 'Default', slug: 'default', dark: true },
  { name: 'Dracula', slug: 'dracula', dark: true },
  { name: 'Espresso', slug: 'espresso', dark: true },
  { name: 'Forest', slug: 'forest', dark: true },
  { name: 'Gruvbox', slug: 'gruvbox', dark: true },
  { name: 'Midnight', slug: 'midnight', dark: true },
  { name: 'Navy', slug: 'navy', dark: true },
  { name: 'Nord', slug: 'nord', dark: true },
  { name: 'Onyx', slug: 'onyx', dark: true },
  { name: 'Rose Pine', slug: 'rose-pine', dark: true },
  { name: 'Slate', slug: 'slate', dark: true },
  { name: 'Coral', slug: 'coral', dark: false },
  { name: 'Dawn', slug: 'dawn', dark: false },
  { name: 'Frost', slug: 'frost', dark: false },
  { name: 'Lavender', slug: 'lavender', dark: false },
  { name: 'Lilac', slug: 'lilac', dark: false },
  { name: 'Mint', slug: 'mint', dark: false },
  { name: 'Peach', slug: 'peach', dark: false },
  { name: 'Rose', slug: 'rose', dark: false },
  { name: 'Sage', slug: 'sage', dark: false },
  { name: 'Silver', slug: 'silver', dark: false },
  { name: 'Sky', slug: 'sky', dark: false },
];
