// AUTO-GENERATED by scripts/gen_ts_types.py — do not edit by hand.
// Source of truth: AssetsManager/lan/dto.py

export interface RuntimeCursor {
  epoch: string;
  revision: number;
}

export interface Capabilities {
  browse: boolean;
  preview: boolean;
  download: boolean;
  upload: boolean;
  manage_links: boolean;
  manage_users: boolean;
  settings: boolean;
  realtime: boolean;
}

export interface InvalidationEvent extends RuntimeCursor {
  type: 'projection_invalidated';
  domains: ProjectionDomain[];
  paths: string[];
}

export interface InviteResponse {
  code: string;
  created_at: number;
  used_by: string | null;
  revoked: boolean;
}

export interface SessionPrincipal {
  kind: 'user' | 'password' | 'access_key' | 'local_ui' | 'guest' | 'share';
  authenticated: boolean;
  role: 'admin' | 'user' | 'guest';
  display_name: string;
  capabilities: Capabilities;
  user_profile?: UserResponse;
}

export interface StatsResponse {
  connections: number;
  requests: number;
  bytes_transferred: number | null;
  bytes_transferred_fmt: string | null;
  uptime: number;
}

export interface Tag {
  id: number | null;
  name: string;
  count: number;
}

export interface TreeItem {
  name: string;
  path: string;
  type: 'dir';
  is_leaf: boolean;
  children: TreeItem[];
}

export interface UserResponse {
  id: number;
  username: string;
  role: 'admin' | 'user';
  active: boolean;
  created_at: number;
}

export type ProjectionDomain =
  | 'files'
  | 'tree'
  | 'home'
  | 'project_detail'
  | 'metadata'
  | 'favorites'
  | 'tags'
  | 'shares'
  | 'users'
  | 'activity'
  | 'online_users'
  | 'shop'
  | 'orders'
  | 'quota';
