#!/usr/bin/env python3
"""Build the per-user Windows installer (Inno Setup) for AssetManager.

Position in the release pipeline: run AFTER ``pyinstaller AssetManager.spec``
has produced the single-file executable at ``dist/AssetManager.exe``. Steps:

1. Read APP_VERSION from ``AssetsManager/core/constants.py`` (single source
   of truth) and stamp ``installer/_version.iss`` with
   ``#define APP_VERSION "x.y.z"`` — the main script ``#include``s it, so the
   installer version always matches the About dialog / exe version resource.
2. Locate ``ISCC.exe``: ``ISCC_PATH`` env var →
   ``%PROGRAMFILES(X86)%\\Inno Setup 6\\ISCC.exe`` → ``PATH``.
3. Statically self-check the .iss (required directives, balanced quotes and
   braces) so a broken script fails here instead of only on CI. Used as the
   local ``--dry-run`` when Inno Setup is not installed.
4. Run ISCC, then write the SHA256 beside the artifact, mirroring the
   release.yml zip discipline: ``<hex>  <filename>`` in ``<name>.sha256``.

Outputs: ``dist/installer/AssetManager-<version>-setup.exe`` and its
``.sha256`` sidecar.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import sys
from collections.abc import Mapping
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONSTANTS = ROOT / "AssetsManager" / "core" / "constants.py"
DEFAULT_ISS = ROOT / "installer" / "assetmanager.iss"
DEFAULT_VERSION_INCLUDE = ROOT / "installer" / "_version.iss"
BUNDLE_EXE = ROOT / "dist" / "AssetManager.exe"

APP_VERSION_RE = re.compile(r'^APP_VERSION\s*=\s*"([^"]+)"', re.MULTILINE)

# Required directives of the per-user installer contract. Kept explicit so an
# accidental edit flipping per-user back to per-machine (or dropping the
# generated version include) fails the static check before any build.
REQUIRED_DIRECTIVES: tuple[str, ...] = (
    "[Setup]",
    "PrivilegesRequired=lowest",
    "DefaultDirName={localappdata}",
    "AppId=",
    "[Files]",
    "[Icons]",
    "[Run]",
)
REQUIRED_INCLUDE = '#include "_version.iss"'


class BuildError(RuntimeError):
    """Fatal installer-build problem with operator-facing guidance."""


def read_app_version(constants_path: Path = CONSTANTS) -> str:
    """Parse APP_VERSION out of constants.py without importing the package."""
    text = constants_path.read_text(encoding="utf-8")
    match = APP_VERSION_RE.search(text)
    if not match:
        raise BuildError(
            f"APP_VERSION not found in {constants_path}; the installer build "
            "requires the single-source version constant."
        )
    return match.group(1)


def write_version_include(
    version: str, include_path: Path = DEFAULT_VERSION_INCLUDE
) -> Path:
    """Stamp the generated ``#define APP_VERSION`` include consumed by the iss."""
    include_path.parent.mkdir(parents=True, exist_ok=True)
    include_path.write_text(
        "; GENERATED by scripts/build_installer.py — do not edit or commit.\n"
        f'#define APP_VERSION "{version}"\n',
        encoding="utf-8",
    )
    return include_path


def locate_iscc(
    env: Mapping[str, str] | None = None, which=shutil.which
) -> Path:
    """Find ISCC.exe in the documented priority order.

    1. ``ISCC_PATH`` environment variable (explicit override),
    2. ``%PROGRAMFILES(X86)%\\Inno Setup 6\\ISCC.exe`` (choco/official setup),
    3. ``PATH`` lookup (choco shims).
    """
    env = os.environ if env is None else env

    override = env.get("ISCC_PATH")
    if override:
        candidate = Path(override)
        if candidate.is_file():
            return candidate
        raise BuildError(f"ISCC_PATH={override} does not point to a file.")

    program_files = env.get("PROGRAMFILES(X86)")
    if program_files:
        candidate = Path(program_files) / "Inno Setup 6" / "ISCC.exe"
        if candidate.is_file():
            return candidate

    found = which("ISCC.exe") or which("iscc")
    if found:
        return Path(found)

    raise BuildError(
        "ISCC.exe not found. Install Inno Setup 6, set ISCC_PATH, or ensure "
        "ISCC.exe is on PATH (choco install innosetup)."
    )


def validate_iss(iss_path: Path = DEFAULT_ISS) -> list[str]:
    """Minimal static self-check of the installer script (no Inno needed).

    Returns a list of problems (empty = clean): required directives present,
    the generated version include wired in, quotes balanced per line, and
    braces balanced overall (Inno escapes a literal open brace by doubling
    it). Full-line ``;`` comments are ignored; the checker does not model
    Inno's ``{ }`` block comments, so the script must not use those.
    """
    problems: list[str] = []
    text = iss_path.read_text(encoding="utf-8")
    # Inno comments are whole lines starting with ';'; a ';' inside a section
    # entry separates parameters and must NOT be treated as a comment.
    stripped_lines = [
        line.strip() for line in text.splitlines()
        if line.strip() and not line.strip().startswith(";")
    ]

    joined = "\n".join(stripped_lines)
    for directive in REQUIRED_DIRECTIVES:
        if directive not in joined:
            problems.append(f"missing required directive: {directive}")
    if REQUIRED_INCLUDE not in joined:
        problems.append(f"missing required include: {REQUIRED_INCLUDE}")

    for number, line in enumerate(stripped_lines, start=1):
        if line.count('"') % 2:
            problems.append(f"unbalanced quotes on line {number}: {line[:60]}")

    # Inno escapes a literal brace by doubling the OPEN only (`AppId={{GUID}`
    # is intentionally 2 opens / 1 close — that line is excluded from the
    # count). A doubled close (`{cm:...,{#X}}`) is two constant closings, not
    # an escape, so only `{{` is collapsed before balancing. Everything else
    # ({app}, {cm:...}, {#Define}, …) must balance.
    brace_text = "\n".join(
        line for line in stripped_lines if not line.startswith("AppId=")
    ).replace("{{", "")
    if brace_text.count("{") != brace_text.count("}"):
        problems.append("unbalanced braces across script (check {…} constants)")

    return problems


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--iss", type=Path, default=DEFAULT_ISS, help="Path to the .iss script."
    )
    parser.add_argument(
        "--version-include",
        type=Path,
        default=DEFAULT_VERSION_INCLUDE,
        help="Where to stamp the generated #define APP_VERSION include.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Stamp the version include, self-check the script and print the "
        "key build facts without invoking ISCC (for hosts without Inno Setup).",
    )
    args = parser.parse_args(argv)

    version = read_app_version()
    include_path = write_version_include(version, args.version_include)
    print(f"version: {version} (from constants.py)")
    print(f"version include: {include_path}")

    problems = validate_iss(args.iss)
    if problems:
        for problem in problems:
            print(f"iss check: {problem}", file=sys.stderr)
        return 1
    print(f"iss check: {args.iss.name} OK ({len(REQUIRED_DIRECTIVES)} directives)")

    if args.dry_run:
        print("dry-run: ISCC invocation skipped (static checks passed).")
        return 0

    if not BUNDLE_EXE.is_file():
        raise BuildError(
            f"{BUNDLE_EXE} not found; run `pyinstaller AssetManager.spec` first."
        )

    iscc = locate_iscc()
    print(f"ISCC: {iscc}")
    import subprocess

    completed = subprocess.run(
        [str(iscc), "/Q", str(args.iss)],
        check=False,
    )
    if completed.returncode != 0:
        raise BuildError(f"ISCC exited with {completed.returncode}.")

    setup = ROOT / "dist" / "installer" / f"AssetManager-{version}-setup.exe"
    if not setup.is_file():
        raise BuildError(f"ISCC reported success but {setup} is missing.")
    checksum_path = setup.with_suffix(".exe.sha256")
    checksum_path.write_text(f"{sha256_file(setup)}  {setup.name}\n", encoding="ascii")
    print(f"installer: {setup}")
    print(f"sha256:    {checksum_path}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BuildError as error:
        print(f"build_installer: {error}", file=sys.stderr)
        sys.exit(1)
