#!/usr/bin/env python3
"""Generate TypeScript contracts from the LAN DTO source of truth (C1).

The nine stable, public ``@dataclass(frozen=True)`` response DTOs in
``AssetsManager/lan/dto.py`` are the single source of truth for the public LAN
API surface.  This script parses that file with :mod:`ast` (so it never
imports the business module, avoiding Qt/IO side effects) and emits a legal,
strict-mode TypeScript interface file at ``webui/src/types/contracts.ts``:

    python scripts/gen_ts_types.py            # (re)generate the .ts file
    python scripts/gen_ts_types.py --check    # compare in-memory output with
                                              # the on-disk file; exit 2 on
                                              # drift without writing anything

The mapping from Python to TypeScript is expressed as three clearly named dict
constants so reviewers can audit the contract at a glance:

    CLASS_NAME_MAP      Python dataclass name -> TS interface name
    LITERAL_OVERRIDE    (class, field) -> literal-union type string to narrow
                        a ``str`` field that only ever carries a fixed set of
                        values on the wire
    FIELD_TYPE_OVERRIDE (class, field) -> rewritten TS type string; an
                        optional marker is encoded as a ``?`` suffix on the
                        field name and excluded fields (``domains``/``paths``
                        of the invalidation response) are widened here.

Two dataclasses are rendered specially rather than mechanically: ``TreeItem``
recurses into itself, and ``ProjectionInvalidationResponse`` is exposed to the
webui as ``InvalidationEvent`` (an extension of ``RuntimeCursor`` carrying an
extra ``type`` discriminant).  ``ProjectionDomain`` is parsed directly from
the backend ``ProjectionDomain`` StrEnum in
``AssetsManager/application/runtime_events.py`` — the generator never holds
its own copy of the domain list.
"""
from __future__ import annotations

import argparse
import ast
import difflib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DTO_PATH = ROOT / "AssetsManager" / "lan" / "dto.py"
RUNTIME_EVENTS_PATH = ROOT / "AssetsManager" / "application" / "runtime_events.py"
CONTRACTS_PATH = ROOT / "webui" / "src" / "types" / "contracts.ts"

HEADER = (
    "// AUTO-GENERATED by scripts/gen_ts_types.py — do not edit by hand.\n"
    "// Source of truth: AssetsManager/lan/dto.py\n"
)

# Python class name -> TypeScript interface name.
CLASS_NAME_MAP: dict[str, str] = {
    "CapabilitiesResponse": "Capabilities",
    "SessionPrincipalResponse": "SessionPrincipal",
    "UserResponse": "UserResponse",
    "InviteResponse": "InviteResponse",
    "TagResponse": "Tag",
    "TreeItemResponse": "TreeItem",
    "StatsResponse": "StatsResponse",
    "RuntimeCursorResponse": "RuntimeCursor",
    "ProjectionInvalidationResponse": "InvalidationEvent",
}

# (class, field) -> literal-union type string.  Narrows a ``str`` field that
# the server only ever emits from a fixed set of values.
LITERAL_OVERRIDE: dict[tuple[str, str], str] = {
    ("SessionPrincipalResponse", "kind"): (
        "'user' | 'password' | 'access_key' | 'local_ui' | 'guest' | 'share'"
    ),
    ("SessionPrincipalResponse", "role"): "'admin' | 'user' | 'guest'",
    ("UserResponse", "role"): "'admin' | 'user'",
    ("TreeItemResponse", "type"): "'dir'",
}

# (class, field) -> rewritten TS type string.  An optional marker is encoded
# as a ``?`` suffix on the field name; all other keys keep the field required.
FIELD_TYPE_OVERRIDE: dict[tuple[str, str], str] = {
    ("SessionPrincipalResponse", "user_profile?"): "UserResponse",
    ("TreeItemResponse", "children"): "TreeItem[]",
    ("ProjectionInvalidationResponse", "domains"): "ProjectionDomain[]",
    ("ProjectionInvalidationResponse", "paths"): "string[]",
}

# ProjectionDomain is parsed from the backend enum; see
# ``_parse_projection_domains`` below. ``domains`` on the invalidation
# response is widened to ``ProjectionDomain[]`` via FIELD_TYPE_OVERRIDE.

_SCALAR_MAP: dict[str, str] = {
    "str": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
}

# Dataclasses whose TS rendering diverges from the mechanical field mapping.
_SPECIAL_RENDERS = frozenset({"TreeItemResponse", "ProjectionInvalidationResponse"})


def _base_name(node: ast.expr) -> str:
    """Return the short name of a generic's base (``tuple`` / ``dict`` ...)."""
    if isinstance(node, ast.Name):
        return node.id or ""
    if isinstance(node, ast.Attribute):
        return node.attr or ""
    return ""


def _unparse(node: ast.expr) -> str:
    """Best-effort literal rendering of an annotation we did not special-case."""
    try:
        return ast.unparse(node)
    except Exception:
        return "unknown"


class _TypeRenderer:
    """Recursively translate a field type annotation (AST) to a TS type.

    ``str``/``int``/``float``/``bool`` are mapped to TS scalars; ``X | None``
    becomes ``X | null``; ``tuple[T, ...]`` (and ``list``/``set``) become
    ``T[]``; ``dict[str, object]`` -> ``Record<string, unknown>`` and
    ``dict[str, bool]`` -> ``Record<string, boolean>``; and a bare dataclass
    reference resolves through ``CLASS_NAME_MAP``.  Anything unhandled is
    unparsed literally so a mismatch is visible rather than silently invented.
    """

    def render(self, node: ast.expr | None) -> str:
        return self._expand(node)

    def _expand(self, node: ast.expr | None) -> str:
        if node is None:
            return "unknown"

        if isinstance(node, ast.BinOp) and isinstance(node.op, ast.BitOr):
            left = self._expand(node.left)
            right = self._expand(node.right)
            if right == "None":
                return f"{left} | null"
            return f"{left} | {right}"

        if isinstance(node, ast.Name):
            if node.id is None:
                return "string"
            if node.id in _SCALAR_MAP:
                return _SCALAR_MAP[node.id]
            return CLASS_NAME_MAP.get(node.id, node.id)

        if isinstance(node, ast.Subscript):
            base = _base_name(node.value)
            if base in ("tuple", "list", "set"):
                return f"{self._expand(node.slice)}[]"
            if base == "dict" and isinstance(node.slice, ast.Tuple) and len(node.slice.elts) == 2:
                key = node.slice.elts[0]
                value = node.slice.elts[1]
                if isinstance(key, ast.Name) and key.id == "str":
                    value_name = value.id if isinstance(value, ast.Name) else ""
                    if value_name == "object":
                        return "Record<string, unknown>"
                    if value_name == "bool":
                        return "Record<string, boolean>"
            return _unparse(node)

        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return "string"

        return _unparse(node)


def _parse_dataclasses(source: str) -> list[tuple[str, list[tuple[str, ast.expr | None]]]]:
    """Return, in source order, (class_name, [(field_name, annotation_node)]).

    Only ``@dataclass(frozen=True)`` class bodies are matched; the TypedDict
    records and module-level helpers are ignored.
    """
    module = ast.parse(source)
    result: list[tuple[str, list[tuple[str, ast.expr | None]]]] = []
    for node in module.body:
        if not isinstance(node, ast.ClassDef):
            continue
        if not any(_is_frozen_dataclass(dec) for dec in node.decorator_list):
            continue
        fields: list[tuple[str, ast.expr | None]] = []
        for stmt in node.body:
            if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                fields.append((stmt.target.id, stmt.annotation))
        if fields:
            result.append((node.name, fields))
    return result


def _is_frozen_dataclass(decorator: ast.expr) -> bool:
    """True for ``@dataclass(frozen=True)`` (bare ``@dataclass`` is excluded)."""
    if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Name):
        if decorator.func.id != "dataclass":
            return False
        for keyword in decorator.keywords:
            if keyword.arg == "frozen" and isinstance(keyword.value, ast.Constant):
                return keyword.value.value is True
    return False


def _render_interface(ts_name: str, fields: list[tuple[str, str]]) -> str:
    lines = [f"export interface {ts_name} {{"]
    for name, ts_type in fields:
        lines.append(f"  {name}: {ts_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_mechanical(
    cls_name: str,
    fields: list[tuple[str, ast.expr | None]],
    renderer: _TypeRenderer,
) -> str:
    """Render a non-special dataclass through the three override dicts."""
    rendered: list[tuple[str, str]] = []
    for field_name, annotation in fields:
        literal_key = (cls_name, field_name)
        optional_key = (cls_name, f"{field_name}?")
        plain_key = (cls_name, field_name)
        if literal_key in LITERAL_OVERRIDE:
            rendered.append((field_name, LITERAL_OVERRIDE[literal_key]))
        elif optional_key in FIELD_TYPE_OVERRIDE:
            rendered.append((f"{field_name}?", FIELD_TYPE_OVERRIDE[optional_key]))
        elif plain_key in FIELD_TYPE_OVERRIDE:
            rendered.append((field_name, FIELD_TYPE_OVERRIDE[plain_key]))
        else:
            rendered.append((field_name, renderer.render(annotation)))
    return _render_interface(CLASS_NAME_MAP[cls_name], rendered)


def _render_special(cls_name: str) -> str:
    """Render the two structural interfaces by hand (recursion / extension)."""
    if cls_name == "TreeItemResponse":
        return (
            "export interface TreeItem {\n"
            "  name: string;\n"
            "  path: string;\n"
            "  type: 'dir';\n"
            "  is_leaf: boolean;\n"
            "  children: TreeItem[];\n"
            "}"
        )
    if cls_name == "ProjectionInvalidationResponse":
        return (
            "export interface InvalidationEvent extends RuntimeCursor {\n"
            "  type: 'projection_invalidated';\n"
            "  domains: ProjectionDomain[];\n"
            "  paths: string[];\n"
            "}"
        )
    raise AssertionError(f"not a special render: {cls_name}")


def _parse_projection_domains(source: str) -> tuple[str, ...]:
    """Extract the ``ProjectionDomain`` StrEnum values from runtime_events.py."""
    module = ast.parse(source)
    for node in module.body:
        if not isinstance(node, ast.ClassDef) or node.name != "ProjectionDomain":
            continue
        domains: list[str] = []
        for statement in node.body:
            if isinstance(statement, ast.Assign):
                for target in statement.targets:
                    if isinstance(target, ast.Name) and isinstance(
                        statement.value, ast.Constant
                    ) and isinstance(statement.value.value, str):
                        domains.append(statement.value.value)
        if domains:
            return tuple(domains)
        break
    raise RuntimeError("ProjectionDomain enum not found in runtime_events.py")


def _render_projection_domain(literals: tuple[str, ...]) -> str:
    values = "\n  | ".join(f"'{literal}'" for literal in literals)
    return "export type ProjectionDomain =\n  | " + values + ";\n"


def generate_contracts_ts() -> str:
    """Generate the full contracts.ts source from ``AssetsManager/lan/dto.py``.

    Returns the file text as a ``str`` with LF line endings.  A pure function
    of the dto source plus the mapping constants, so callers can diff its
    output against disk without side effects.
    """
    source = DTO_PATH.read_text(encoding="utf-8")
    classes = _parse_dataclasses(source)
    renderer = _TypeRenderer()
    projection_domains = _parse_projection_domains(
        RUNTIME_EVENTS_PATH.read_text(encoding="utf-8")
    )

    blocks: dict[str, str] = {}
    for cls_name, fields in classes:
        if cls_name in _SPECIAL_RENDERS:
            blocks[CLASS_NAME_MAP[cls_name]] = _render_special(cls_name)
        elif cls_name in CLASS_NAME_MAP:
            blocks[CLASS_NAME_MAP[cls_name]] = _render_mechanical(cls_name, fields, renderer)

    # Emit RuntimeCursor first (InvalidationEvent extends it), then the rest in
    # stable alphabetical order by TS interface name, then the domain union.
    parts = [HEADER, blocks["RuntimeCursor"] + "\n"]
    for name in sorted(blocks):
        if name == "RuntimeCursor":
            continue
        parts.append(blocks[name] + "\n")
    parts.append(_render_projection_domain(projection_domains))
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate/verify webui/src/types/contracts.ts from the LAN DTO."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify against disk instead of writing; exit 2 on drift",
    )
    args = parser.parse_args()

    generated = generate_contracts_ts()

    if args.check:
        on_disk = CONTRACTS_PATH.read_text(encoding="utf-8") if CONTRACTS_PATH.exists() else ""
        if on_disk == generated:
            print("contracts.ts is up to date")
            return 0
        diff = difflib.unified_diff(
            on_disk.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(CONTRACTS_PATH),
            tofile="<generated>",
        )
        sys.stderr.writelines(diff)
        print("contracts.ts is out of date; run scripts/gen_ts_types.py", file=sys.stderr)
        return 2

    CONTRACTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONTRACTS_PATH.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {CONTRACTS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
