#!/usr/bin/env python3
"""Generate Web CSS design tokens from the desktop theme JSON single source (S4).

Reads the canonical ``Assets/Themes/*.json`` palettes and emits two artifacts:

1. ``webui/src/tokens/themes.generated.css`` — the ``:root`` (D_Navy) /
   ``html.light`` (L_Dawn) fallback blocks consumed by the WebUI, plus a full
   variable block for every shipped theme under
   ``html[data-am-theme="<slug>"]`` (slug = kebab-cased theme name, e.g.
   "Rose Pine" -> "rose-pine"). The LAN backend reports the owner's current
   theme display name via ``/api/info theme_name`` and the WebUI applies the
   matching ``data-am-theme`` attribute so guests see the owner's palette
   identity (with the light/dark toggle still available as a mode override).

2. ``webui/src/tokens/themes.manifest.generated.ts`` — the same theme set as
   a TypeScript manifest (``{name, slug, dark}``) so the WebUI can map
   ``theme_name`` to a slug and a default mode without duplicating the list.

The desktop PySide layer already consumes the same JSONs through
``core/themes.py``, so a change to a shipped palette updates all surfaces
from one file.

    python scripts/gen_web_tokens.py            # (re)generate
    python scripts/gen_web_tokens.py --check    # exit 2 on drift without writing
"""
from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
THEMES_DIR = ROOT / "Assets" / "Themes"
DARK_THEME = "D_Navy.json"
LIGHT_THEME = "L_Dawn.json"
OUTPUT_PATH = ROOT / "webui" / "src" / "tokens" / "themes.generated.css"
MANIFEST_PATH = ROOT / "webui" / "src" / "tokens" / "themes.manifest.generated.ts"

HEADER = (
    "/* AUTO-GENERATED by scripts/gen_web_tokens.py — do not edit by hand.\n"
    "   Source of truth: Assets/Themes/*.json (shared with PySide core/themes.py). */\n"
)

MANIFEST_HEADER = (
    "// AUTO-GENERATED by scripts/gen_web_tokens.py — do not edit by hand.\n"
    "// Source of truth: Assets/Themes/*.json (shared with PySide core/themes.py).\n"
    "// WebUI consumes this to map /api/info theme_name to the data-am-theme\n"
    "// slug emitted in themes.generated.css; keep both artifacts in sync by\n"
    "// regenerating, never by hand-editing.\n"
)

# CSS variable -> theme JSON color key.
COLOR_MAP: dict[str, str] = {
    "--color-bg": "base",
    "--color-surface": "panel",
    "--color-surface-hover": "header",
    "--color-elevated": "header",
    "--color-border": "border",
    "--color-border-strong": "border",
    "--color-border-focus": "border_focus",
    "--color-text": "heading",
    "--color-text-secondary": "body",
    "--color-text-muted": "muted",
    "--color-text-inverse": "on_accent",
    "--color-accent": "accent",
    "--color-accent-hover": "accent",
    "--color-success": "success",
    "--color-success-text": "success",
    "--color-warning": "warning",
    "--color-warning-text": "warning",
    "--color-danger": "danger",
    "--color-danger-text": "danger",
    "--color-info": "accent",
    "--scrollbar-track": "scrollbar_track",
    "--scrollbar-thumb": "scrollbar_thumb",
    "--scrollbar-thumb-hover": "scrollbar_thumb_hover",
    "--skeleton-bg": "disabled_bg",
    "--input-bg": "input_bg",
    "--input-border": "border",
    "--input-focus-border": "border_focus",
}

# (css variable, source color key, alpha) for alpha composited token pairs.
ALPHA_MAP: dict[str, tuple[str, float]] = {
    "--color-accent-subtle": ("accent", 0.10),
    "--color-accent-border": ("accent", 0.30),
    "--color-success-subtle": ("success", 0.10),
    "--color-warning-subtle": ("warning", 0.10),
    "--color-danger-subtle": ("danger", 0.10),
    "--color-danger-border": ("danger", 0.30),
    # Muted surface for image placeholders / secondary wells (seller gallery
    # editor, storefront cart lines). Derived from disabled_bg at ~55% over
    # --color-surface so it stays a subtle step down from the panel in both
    # themes while --color-text-secondary keeps >=8:1 contrast on the
    # composited result (dark ~#161823, light ~#f0ebe2).
    "--color-surface-muted": ("disabled_bg", 0.55),
}

# Scrim tokens the generator owns outright. An overlay is a *covering*
# semantic (dimming the page behind Modal / mobile-drawer / command-palette
# scrims), not a panel color, so it deliberately does not come from the theme
# JSONs — the desktop palettes have no such key. Both values sit in the
# deepest archive-background ink family (cf. DESIGN.md --gate-bg-deepest
# #07070d); the light theme uses a lower alpha so warm surfaces stay readable
# behind a dialog instead of turning into a heavy gray wash.
OVERLAY_INK: dict[bool, tuple[str, float]] = {
    False: ("#07070d", 0.62),  # dark theme
    True: ("#14141e", 0.42),  # light theme
}

_SLUG_SANITIZE_RE = re.compile(r"[^a-z0-9]+")


def _load_theme_file(filename: str) -> dict:
    path = THEMES_DIR / filename
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    colors = data.get("colors")
    if not isinstance(colors, dict):
        raise RuntimeError(f"{filename}: missing colors block")
    name = data.get("name")
    if not isinstance(name, str) or not name:
        raise RuntimeError(f"{filename}: missing theme name")
    for key in COLOR_MAP.values():
        if key not in colors:
            raise RuntimeError(f"{filename}: missing color token '{key}'")
    for key, _alpha in ALPHA_MAP.values():
        if key not in colors:
            raise RuntimeError(f"{filename}: missing color token '{key}'")
    return data


def _load_colors(filename: str) -> dict[str, str]:
    return _load_theme_file(filename)["colors"]


def theme_slug(name: str) -> str:
    """Kebab-case a theme display name: "Rose Pine" -> "rose-pine"."""
    slug = _SLUG_SANITIZE_RE.sub("-", name.strip().lower()).strip("-")
    if not slug:
        raise RuntimeError(f"theme name {name!r} produces an empty slug")
    return slug


def iter_themes() -> list[dict]:
    """Load every shipped theme, sorted by filename for stable output."""
    themes: list[dict] = []
    for path in sorted(THEMES_DIR.glob("*.json")):
        data = _load_theme_file(path.name)
        data["_file"] = path.name
        data["_slug"] = theme_slug(data["name"])
        themes.append(data)
    if not themes:
        raise RuntimeError(f"no theme JSONs found under {THEMES_DIR}")
    slugs = [t["_slug"] for t in themes]
    duplicates = sorted({slug for slug in slugs if slugs.count(slug) > 1})
    if duplicates:
        raise RuntimeError(f"duplicate theme slugs: {duplicates}")
    return themes


def _rgba(hex_color: str, alpha: float) -> str:
    value = hex_color.lstrip("#")
    if len(value) == 3:
        value = "".join(ch * 2 for ch in value)
    r, g, b = (int(value[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


def _render_block(colors: dict[str, str], light: bool, selector: str | None = None) -> str:
    """Render one variable block.

    ``selector=None`` keeps the two fallback blocks (``:root`` for the dark
    default, ``html.light`` for the light default); per-theme identity blocks
    pass ``html[data-am-theme="<slug>"]``.
    """
    lines = [f"{selector} {{"] if selector else ["html.light {" if light else ":root {"]
    for css_var, color_key in COLOR_MAP.items():
        lines.append(f"  {css_var}: {colors[color_key]};")
    ink, alpha = OVERLAY_INK[light]
    lines.append(f"  --color-overlay: {_rgba(ink, alpha)};")
    for css_var, (color_key, alpha) in ALPHA_MAP.items():
        lines.append(f"  {css_var}: {_rgba(colors[color_key], alpha)};")
    lines.append(f"  color-scheme: {'light' if light else 'dark'};")
    lines.append("}")
    return "\n".join(lines)


def generate_css() -> str:
    dark = _load_colors(DARK_THEME)
    light = _load_colors(LIGHT_THEME)
    parts = [HEADER, "\n", _render_block(dark, light=False), "\n\n", _render_block(light, light=True)]
    # Per-theme identity blocks must come after the fallback blocks: they tie
    # with ``html.light`` on specificity (0,1,1) and win on source order, so
    # a matched owner theme always paints its own palette over the L_Dawn
    # fallback. They intentionally do NOT emit --color-accent-text: that
    # contrast-safe text token stays owned by index.css per light/dark mode.
    for theme in iter_themes():
        light_theme = theme.get("dark") is not True
        colors = theme["colors"]
        parts.append("\n\n")
        parts.append(_render_block(
            colors, light=light_theme,
            selector=f'html[data-am-theme="{theme["_slug"]}"]',
        ))
    parts.append("\n")
    return "".join(parts)


def generate_manifest() -> str:
    lines = [MANIFEST_HEADER]
    lines.append("export const THEMES: { name: string; slug: string; dark: boolean }[] = [")
    for theme in iter_themes():
        name = theme["name"].replace("\\", "\\\\").replace("'", "\\'")
        dark = theme.get("dark") is not False
        lines.append(f"  {{ name: '{name}', slug: '{theme['_slug']}', dark: {str(dark).lower()} }},")
    lines.append("];\n")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify drift without writing")
    args = parser.parse_args()

    generated = generate_css()
    manifest = generate_manifest()
    if args.check:
        exit_code = 0
        for path, content, label in (
            (OUTPUT_PATH, generated, "themes.generated.css"),
            (MANIFEST_PATH, manifest, "themes.manifest.generated.ts"),
        ):
            on_disk = path.read_text(encoding="utf-8") if path.exists() else ""
            if on_disk == content:
                print(f"{label} is up to date")
                continue
            diff = difflib.unified_diff(
                on_disk.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(path),
                tofile="<generated>",
            )
            sys.stderr.writelines(diff)
            print(f"{label} is out of date; run scripts/gen_web_tokens.py", file=sys.stderr)
            exit_code = 2
        return exit_code
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH}")
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(manifest, encoding="utf-8", newline="\n")
    print(f"wrote {MANIFEST_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
