#!/usr/bin/env python3
"""Generate Web CSS design tokens from the desktop theme JSON single source (S4).

Reads the canonical ``Assets/Themes/*.json`` palettes (dark = D_Navy, light =
L_Dawn) and emits ``webui/src/tokens/themes.generated.css`` containing the
``:root`` / ``html.light`` color variables consumed by the WebUI. The desktop
PySide layer already consumes the same JSONs through ``core/themes.py``, so a
change to a shipped palette updates both surfaces from one file.

    python scripts/gen_web_tokens.py            # (re)generate
    python scripts/gen_web_tokens.py --check    # exit 2 on drift without writing
"""
from __future__ import annotations

import argparse
import difflib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
THEMES_DIR = ROOT / "Assets" / "Themes"
DARK_THEME = "D_Navy.json"
LIGHT_THEME = "L_Dawn.json"
OUTPUT_PATH = ROOT / "webui" / "src" / "tokens" / "themes.generated.css"

HEADER = (
    "/* AUTO-GENERATED by scripts/gen_web_tokens.py — do not edit by hand.\n"
    "   Source of truth: Assets/Themes/*.json (shared with PySide core/themes.py). */\n"
)

# CSS variable -> theme JSON color key.
COLOR_MAP: dict[str, str] = {
    "--color-bg": "base",
    "--color-surface": "panel",
    "--color-surface-hover": "header",
    "--color-elevated": "header",
    "--color-border": "border",
    "--color-border-strong": "border",
    "--color-border-focus": "border_focus",
    "--color-text": "heading",
    "--color-text-secondary": "body",
    "--color-text-muted": "muted",
    "--color-text-inverse": "on_accent",
    "--color-accent": "accent",
    "--color-accent-hover": "accent",
    "--color-success": "success",
    "--color-success-text": "success",
    "--color-warning": "warning",
    "--color-warning-text": "warning",
    "--color-danger": "danger",
    "--color-danger-text": "danger",
    "--color-info": "accent",
    "--scrollbar-track": "scrollbar_track",
    "--scrollbar-thumb": "scrollbar_thumb",
    "--scrollbar-thumb-hover": "scrollbar_thumb_hover",
    "--skeleton-bg": "disabled_bg",
    "--input-bg": "input_bg",
    "--input-border": "border",
    "--input-focus-border": "border_focus",
}

# (css variable, source color key, alpha) for alpha composited token pairs.
ALPHA_MAP: dict[str, tuple[str, float]] = {
    "--color-accent-subtle": ("accent", 0.10),
    "--color-accent-border": ("accent", 0.30),
    "--color-success-subtle": ("success", 0.10),
    "--color-warning-subtle": ("warning", 0.10),
    "--color-danger-subtle": ("danger", 0.10),
    "--color-danger-border": ("danger", 0.30),
}


def _load_colors(filename: str) -> dict[str, str]:
    path = THEMES_DIR / filename
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    colors = data.get("colors")
    if not isinstance(colors, dict):
        raise RuntimeError(f"{filename}: missing colors block")
    return colors


def _rgba(hex_color: str, alpha: float) -> str:
    value = hex_color.lstrip("#")
    if len(value) == 3:
        value = "".join(ch * 2 for ch in value)
    r, g, b = (int(value[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r}, {g}, {b}, {alpha:.2f})"


def _render_block(colors: dict[str, str], light: bool) -> str:
    lines = ["html.light {" if light else ":root {"]
    for css_var, color_key in COLOR_MAP.items():
        lines.append(f"  {css_var}: {colors[color_key]};")
    for css_var, (color_key, alpha) in ALPHA_MAP.items():
        lines.append(f"  {css_var}: {_rgba(colors[color_key], alpha)};")
    lines.append(f"  color-scheme: {'light' if light else 'dark'};")
    lines.append("}")
    return "\n".join(lines)


def generate_css() -> str:
    dark = _load_colors(DARK_THEME)
    light = _load_colors(LIGHT_THEME)
    return HEADER + "\n" + _render_block(dark, light=False) + "\n\n" + _render_block(light, light=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify drift without writing")
    args = parser.parse_args()

    generated = generate_css()
    if args.check:
        on_disk = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if on_disk == generated:
            print("themes.generated.css is up to date")
            return 0
        diff = difflib.unified_diff(
            on_disk.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(OUTPUT_PATH),
            tofile="<generated>",
        )
        sys.stderr.writelines(diff)
        print("themes.generated.css is out of date; run scripts/gen_web_tokens.py", file=sys.stderr)
        return 2
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
