import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronDown, ChevronRight, ChevronsDownUp, ChevronsUpDown, FileText, Folder, Search } from 'lucide-react';
import { useAuth } from '../../hooks/useAuth';
import { useI18n } from '../../hooks/useI18n';
import { createMetadataApi } from '../../api/metadata';
import { useInvalidation } from '../../hooks/useInvalidation';
import type { TreeItem } from '../../types/api';

interface SidebarProps { onNavigate: (path: string) => void; currentPath: string; }
const matchesFilter = (node: TreeItem, filter: string): boolean => !filter || node.name.toLowerCase().includes(filter.toLowerCase()) || node.children?.some(child => matchesFilter(child, filter)) === true;
function collectExpandablePaths(nodes: TreeItem[]): Set<string> { const paths = new Set<string>(); for (const node of nodes) if (node.children?.length) { paths.add(node.path); for (const path of collectExpandablePaths(node.children)) paths.add(path); } return paths; }
function collectActiveAncestors(nodes: TreeItem[], currentPath: string): Set<string> { const paths = new Set<string>(); if (!currentPath) return paths; for (const node of nodes) if (node.children?.length && (currentPath === node.path || currentPath.startsWith(`${node.path}/`))) { paths.add(node.path); for (const path of collectActiveAncestors(node.children, currentPath)) paths.add(path); } return paths; }
function TreeNode({ node, depth, expandedPaths, onToggle, onNavigate, onNavigateDetail, currentPath, filter }: { node: TreeItem; depth: number; expandedPaths: Set<string>; onToggle: (path: string) => void; onNavigate: (path: string) => void; onNavigateDetail: (path: string) => void; currentPath: string; filter: string; }) {
  const isLeaf = node.is_leaf === true; const hasChildren = !!node.children?.length; const isFiltering = Boolean(filter); const expanded = expandedPaths.has(node.path) || isFiltering; const { t } = useI18n(); if (!matchesFilter(node, filter)) return null;
  return <div><div className="relative min-h-8"><button type="button" data-testid={`tree-node-row-${node.path}`} className={`flex min-h-8 w-full min-w-0 items-center gap-1.5 px-2 text-left text-xs transition-colors ${currentPath === node.path ? 'bg-indigo-500/10 text-indigo-300' : 'text-slate-400 hover:bg-slate-800 hover:text-slate-200'}`} onClick={() => isLeaf ? onNavigateDetail(node.path) : onNavigate(node.path)}><span aria-hidden="true" data-testid={`tree-node-indent-${node.path}`} className="flex-shrink-0" style={{ width: `${depth * 14 + 16}px` }} /><span className="flex-shrink-0" data-testid={`tree-node-icon-${node.path}`}>{isLeaf ? <FileText size={14} className="text-indigo-400" /> : <Folder size={14} className="text-amber-400" />}</span><span className="block truncate">{node.name}</span></button>{hasChildren && <button type="button" aria-label={t(expanded ? 'sidebar.collapseNode' : 'sidebar.expandNode', node.name)} aria-disabled={isFiltering} aria-expanded={expanded} disabled={isFiltering} title={isFiltering ? t('sidebar.clearFilterToChangeExpansion') : undefined} onClick={event => { event.stopPropagation(); onToggle(node.path); }} className="absolute top-1/2 z-10 flex h-4 w-4 -translate-y-1/2 items-center justify-center text-slate-500 hover:text-slate-300" style={{ left: `${8 + depth * 14}px` }}>{expanded ? <ChevronDown size={13} /> : <ChevronRight size={13} />}</button>}</div>{hasChildren && expanded && node.children!.map(child => <TreeNode key={child.path} node={child} depth={depth + 1} expandedPaths={expandedPaths} onToggle={onToggle} onNavigate={onNavigate} onNavigateDetail={onNavigateDetail} currentPath={currentPath} filter={filter} />)}</div>;
}
export function Sidebar({ onNavigate, currentPath }: SidebarProps) {
  const [tree, setTree] = useState<TreeItem[]>([]); const [expandedPaths, setExpandedPaths] = useState<Set<string>>(() => new Set()); const [filter, setFilter] = useState(''); const [loading, setLoading] = useState(true); const { api } = useAuth(); const { t } = useI18n(); const navigate = useNavigate(); const metaApi = useMemo(() => createMetadataApi(api), [api]);
  const requestGeneration = useRef(0);
  const mounted = useRef(true);
  const refreshTree = useCallback(() => {
    if (!mounted.current) return;
    const generation = ++requestGeneration.current;
    setLoading(true);
    metaApi.getTree().then(res => { if (mounted.current && generation === requestGeneration.current) setTree(res.tree ?? []); }).catch(() => {}).finally(() => { if (mounted.current && generation === requestGeneration.current) setLoading(false); });
  }, [metaApi]);
  useEffect(() => {
    mounted.current = true;
    refreshTree();
    return () => { mounted.current = false; requestGeneration.current += 1; };
  }, [refreshTree]);
  useInvalidation(['tree'], () => { void refreshTree(); });
  useEffect(() => { const ancestors = collectActiveAncestors(tree, currentPath); if (ancestors.size) setExpandedPaths(paths => new Set([...paths, ...ancestors])); }, [currentPath, tree]);
  const togglePath = useCallback((path: string) => setExpandedPaths(paths => { const next = new Set(paths); if (next.has(path)) next.delete(path); else next.add(path); return next; }), []); const expandAll = useCallback(() => setExpandedPaths(collectExpandablePaths(tree)), [tree]); const collapseAll = useCallback(() => setExpandedPaths(new Set()), []); const isFiltering = Boolean(filter);
  return <div className="flex flex-col h-full"><div className="border-b border-slate-700 bg-slate-900 p-2"><div className="flex items-center justify-between gap-2 mb-2"><h2 className="text-xs font-medium text-slate-300">{t('sidebar.folders')}</h2><div className="flex items-center gap-1"><button type="button" aria-label={t('sidebar.expandAll')} aria-disabled={isFiltering} disabled={isFiltering} title={isFiltering ? t('sidebar.clearFilterToChangeExpansion') : undefined} onClick={expandAll} className="flex h-10 w-10 items-center justify-center text-slate-400 disabled:cursor-not-allowed disabled:opacity-50"><ChevronsUpDown size={14} /></button><button type="button" aria-label={t('sidebar.collapseAll')} aria-disabled={isFiltering} disabled={isFiltering} title={isFiltering ? t('sidebar.clearFilterToChangeExpansion') : undefined} onClick={collapseAll} className="flex h-10 w-10 items-center justify-center text-slate-400 disabled:cursor-not-allowed disabled:opacity-50"><ChevronsDownUp size={14} /></button></div></div><div className="relative"><Search size={13} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-500" /><input type="text" value={filter} onChange={e => setFilter(e.target.value)} aria-label={t('sidebar.search')} placeholder={t('sidebar.search')} className="w-full border border-slate-700 bg-slate-800 py-1.5 pl-8 pr-2 text-xs text-slate-300" /></div></div><div className="flex-1 overflow-auto py-1">{loading ? <div className="space-y-1.5 p-2">{[1, 2, 3, 4, 5].map(i => <div key={i} className="h-6 bg-slate-800 animate-pulse" />)}</div> : tree.length === 0 ? <p className="text-xs text-slate-500 text-center mt-4">{t('sidebar.no_results')}</p> : tree.map(node => <TreeNode key={node.path} node={node} depth={0} expandedPaths={expandedPaths} onToggle={togglePath} onNavigate={onNavigate} onNavigateDetail={path => navigate(`/detail?path=${encodeURIComponent(path)}`)} currentPath={currentPath} filter={filter} />)}</div></div>;
}
